spring:
  application:
    name: backend
  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  expiration: 3600000 # 1 hour
  temporary-expiration: 300000 # 5 minutes

springdoc:
  api-docs:
    path: /docs/api
  swagger-ui:
    path: /docs/swagger-ui.html
    operationsSorter: method

key:
  chatbot: ${API_KEY_CHATBOT}
  gov: ${API_KEY_GOV}
  google: ${API_KEY_GOOGLE}
