spring:
  #  datasource:
  #    url: jdbc:h2:tcp://${DB_HOST}/${DB_NAME}
  #    username: ${DB_USERNAME}
  #    password: ${DB_PASSWORD}
  #    driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:h2:mem:testDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
