spring:
  application:
    name: backend
  jackson:
    property-naming-strategy: SNAKE_CASE
  sql:
    init:
      encoding: UTF-8

jwt:
  expiration: 3600000 # 1 hour
  temporary-expiration: 300000 # 5 minutes

springdoc:
  api-docs:
    path: /docs/api
  swagger-ui:
    path: /docs/swagger-ui.html
    operationsSorter: method

key:
  chatbot: ${API_KEY_CHATBOT}
  gov: ${API_KEY_GOV}
  kakao: ${API_KEY_KAKAO}
  google: ${API_KEY_GOOGLE}

file:
  upload-dir: ${user.home}/tourapi24/uploads
