spring:
  application:
    name: backend
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:h2:tcp://localhost//Volumes/personal/development/project/tourapi-24/backend/h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

jwt:
  expiration: 3600000 # 1 hour
  temporary-expiration: 300000 # 5 minutes

springdoc:
  api-docs:
    path: /docs/api
  swagger-ui:
    path: /docs/swagger-ui.html
    operationsSorter: method

#tourApi: D6W8nGJU7JFd%2FcCsN94xK9U7ifXSnMCQ%2B7AHAVNjzIMhUdXeVkA2Cg0enSw2V9hxvnRuuwP7N42X%2BdD%2BfM0bFA%3D%3D

api:
  tour: D6W8nGJU7JFd%2FcCsN94xK9U7ifXSnMCQ%2B7AHAVNjzIMhUdXeVkA2Cg0enSw2V9hxvnRuuwP7N42X%2BdD%2BfM0bFA%3D%3D
#  google: AIzaSyCfjBEtpw62cHRX1D2tJN1zyBee5WKZQ9A
  google: https://maps.googleapis.com/maps/api/directions/json?mode=transit&key=AIzaSyCfjBEtpw62cHRX1D2tJN1zyBee5WKZQ9A&language=ko
